// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricingEngine_Api.Db;

#nullable disable

namespace PricingEngine_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230227201217_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PricingEngine_Api.Db.Entities.DataBaseInput", b =>
                {
                    b.Property<int>("DataBaseInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataBaseInputId"));

                    b.Property<decimal>("CapitalRiskRateWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditRiskAllocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaintenanceRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaymentRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DataBaseInputId");

                    b.ToTable("DataBaseInputs");
                });

            modelBuilder.Entity("PricingEngine_Api.Db.Entities.UserInput", b =>
                {
                    b.Property<int>("UserInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserInputId"));

                    b.Property<int>("AvgMonthlyFeeIncome")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommitmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiaxountFromStandardFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestSpread")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InterestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyFeeIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OriginalTermInMonths")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeaserPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("TeaserSpread")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserInputId");

                    b.ToTable("UserInputs");
                });
#pragma warning restore 612, 618
        }
    }
}
