// <auto-generated />
using System;
using BonusManagementSystem_Api.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonusManagementSystemApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BonusManagementSystem_Api.Db.Entity.BonusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BonusIssueTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("BonusQuantity")
                        .HasColumnType("float");

                    b.Property<int?>("EmployeeEntityId")
                        .HasColumnType("int");

                    b.Property<int>("recomendtorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeEntityId");

                    b.ToTable("bonuses");
                });

            modelBuilder.Entity("BonusManagementSystem_Api.Db.Entity.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrivateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecomedatorId")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("BonusManagementSystem_Api.Db.Entity.BonusEntity", b =>
                {
                    b.HasOne("BonusManagementSystem_Api.Db.Entity.EmployeeEntity", null)
                        .WithMany("Bonus")
                        .HasForeignKey("EmployeeEntityId");
                });

            modelBuilder.Entity("BonusManagementSystem_Api.Db.Entity.EmployeeEntity", b =>
                {
                    b.Navigation("Bonus");
                });
#pragma warning restore 612, 618
        }
    }
}
